=== cosimameyer/awesome-pyladies-blogs/scripts/.chapter_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name":    { "type": "string" },
    "city":    { "type": "string" },
    "country": { "type": "string" },
    "email":   { "type": "string" },
    "website":   { "type": "string" },
    "photo_url": { "type": "string" },
    "social_media": {
      "type": "object",
      "properties": {
        "twitter":   { "type": "string" },
        "facebook":  { "type": "string" },
        "github":    { "type": "string" },
        "linkedin":  { "type": "string" },
        "instagram": { "type": "string" },
        "meetup":    { "type": "string" },
        "mastodon":  { "type": "string" },
        "bluesky":   { "type": "string" },
        "youtube":   { "type": "string" }
      },
      "additionalProperties": false
    }
  },
  "required": ["name", "city", "country"],
  "additionalProperties": false
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-la-paz-bolivia.json
{
  "name": "PyLadies La Paz",
  "city": "La Paz",
  "country": "Bolivia",
  "email": "lp@pyladies.com",
  "website": "https://www.meetup.com/La-Paz-PyLadies-Meetup",
  "photo_url": "https://pyladies.com/assets/images/pyladies_lapaz.png",
  "social_media": {
    "twitter": "https://twitter.com/PyLadiesLaPaz",
    "facebook": "https://facebook.com/PyLadiesLaPaz"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-silicon-valley-ca.json
{
  "name": "PyLadies Silicon Valley",
  "city": "Silicon Valley",
  "country": "USA",
  "email": "siliconvalley@pyladies.com",
  "website": "http://siliconvalley.pyladies.com",
  "social_media": {
    "github": "https://github.com/SiliconValleyPyLadies",
    "facebook": "https://facebook.com/svpyladies",
    "meetup": "https://www.meetup.com/PyLadies-Silicon-Valley/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-brisbane-australia.json
{
  "name": "PyLadies Brisbane",
  "city": "Brisbane",
  "country": "Australia",
  "email": "brisbane@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/BPLlogo.png",
  "social_media": {
    "github": "https://github.com/BrisbanePyLadies",
    "twitter": "https://twitter.com/PyLadiesBNE",
    "linkedin": "https://www.linkedin.com/company/pyladiesbrisbane/",
    "meetup": "https://www.meetup.com/BrisbanePyLadies/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-chicago-il.json
{
  "name": "PyLadies Chicago",
  "city": "Chicago",
  "country": "USA",
  "email": "chicago@pyladies.com",
  "website": "http://chicago.pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_chicago.png",
  "social_media": {
    "twitter": "https://twitter.com/PyLadiesChicago",
    "meetup": "https://www.meetup.com/Chicago-PyLadies/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-chennai-india.json
{
  "name": "PyLadies Chennai",
  "city": "Chennai",
  "country": "India",
  "email": "chn@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_chennai.png",
  "social_media": {
    "github": "https://github.com/pyladieschennai",
    "twitter": "https://twitter.com/pyladieschennai",
    "facebook": "https://facebook.com/pyladiesofchennai",
    "meetup": "https://www.meetup.com/pyladieschennai/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-pune-india.json
{
  "name": "PyLadies Pune",
  "city": "Pune",
  "country": "India",
  "email": "pune@pyladies.com",
  "website": "http://pune.pyladies.com/",
  "social_media": {
    "twitter": "https://twitter.com/PyladiesPune",
    "facebook": "https://facebook.com/PyLadiesPune",
    "meetup": "https://www.meetup.com/PyLadies-Pune/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-guatemala-city-guatemala.json
{
  "name": "PyLadies Guatemala City",
  "city": "Guatemala City",
  "country": "Guatemala",
  "email": "guatemalacity@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies-guatemala_city.jpg",
  "social_media": {
    "twitter": "https://twitter.com/PyLadiesGTCity",
    "facebook": "https://facebook.com/PyladiesGTCity",
    "instagram": "https://www.instagram.com/PyLadiesGTCity/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-bangalore-india.json
{
  "name": "PyLadies Bangalore",
  "city": "Bangalore",
  "country": "India",
  "email": "pyblr@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_blr_logo.jpeg",
  "social_media": {
    "twitter": "https://twitter.com/pyladiesblr",
    "meetup": "https://www.meetup.com/PyLadies-Bangalore-Chapter/"
  }
}
