=== cosimameyer/awesome-pyladies-blogs/scripts/.chapter_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name":    { "type": "string" },
    "city":    { "type": "string" },
    "country": { "type": "string" },
    "email":   { "type": "string" },
    "website":   { "type": "string" },
    "photo_url": { "type": "string" },
    "social_media": {
      "type": "object",
      "properties": {
        "twitter":   { "type": "string" },
        "facebook":  { "type": "string" },
        "github":    { "type": "string" },
        "linkedin":  { "type": "string" },
        "instagram": { "type": "string" },
        "meetup":    { "type": "string" },
        "mastodon":  { "type": "string" },
        "bluesky":   { "type": "string" },
        "youtube":   { "type": "string" }
      },
      "additionalProperties": false
    }
  },
  "required": ["name", "city", "country"],
  "additionalProperties": false
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-brno-czech-republic.json
{
  "name": "PyLadies Brno",
  "city": "Brno",
  "country": "Czech Republic",
  "email": "brno@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_sd_brno.png",
  "social_media": {
    "twitter": "https://twitter.com/pyladiesCZ",
    "meetup": "https://www.meetup.com/pyladiescz/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-recife-brazil.json
{
  "name": "PyLadies Recife",
  "city": "Recife",
  "country": "Brazil",
  "email": "recife@pyladies.org",
  "website": "http://brasil.pyladies.com",
  "social_media": {
    "github": "https://github.com/pyladies-brazil",
    "twitter": "https://twitter.com/pyladiesrecife",
    "facebook": "https://facebook.com/PyLadies-Recife"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-south-florida-usa.json
{
  "name": "PyLadies South Florida",
  "city": "South Florida",
  "country": "USA",
  "email": "southflorida@pyladies.com",
  "social_media": {
    "github": "https://github.com/PyLadiesSoFlo",
    "twitter": "https://twitter.com/PyLadiesSoFlo",
    "facebook": "https://facebook.com/PyLadiesSoFlo",
    "meetup": "https://www.meetup.com/PyLadies-SoFlo/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-santiago-chile.json
{
  "name": "PyLadies Santiago",
  "city": "Santiago",
  "country": "Chile",
  "email": "santiago@pyladies.com",
  "social_media": {
    "twitter": "https://twitter.com/pyladiesSCL",
    "facebook": "https://facebook.com/@pyladiesSCL",
    "instagram": "https://www.instagram.com/pyladiesSCL/",
    "meetup": "https://www.meetup.com/pyladies-santiago-de-chile/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-asaba-nigeria.json
{
  "name": "PyLadies Asaba",
  "city": "Asaba",
  "country": "Nigeria",
  "email": "asaba@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies-asaba.png",
  "social_media": {
    "github": "https://github.com/Pyladiesasaba",
    "twitter": "https://twitter.com/Pyladiesasaba",
    "facebook": "https://facebook.com/asabapyladies"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-rio-de-janeiro-brazil.json
{
  "name": "PyLadies Rio de Janeiro",
  "city": "Rio de Janeiro",
  "country": "Brazil",
  "email": "brasil@pyladies.org",
  "website": "http://brasil.pyladies.com",
  "social_media": {
    "github": "https://github.com/pyladies-brazil",
    "twitter": "https://twitter.com/rio_pyladies",
    "facebook": "https://facebook.com/PyLadiesRio"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-melbourne-australia.json
{
  "name": "PyLadies Melbourne",
  "city": "Melbourne",
  "country": "Australia",
  "email": "melbourne@pyladies.com",
  "website": "http://melbourne.pyladies.com/",
  "photo_url": "https://pyladies.com/assets/images/pyladies_melbourne.jpeg",
  "social_media": {
    "github": "https://github.com/pyladiesmelbourne",
    "twitter": "https://twitter.com/PyLadiesMEL",
    "facebook": "https://facebook.com/pyladiesau",
    "meetup": "https://www.meetup.com/PyLadies-Melbourne/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-curitiba-brazil.json
{
  "name": "PyLadies Curitiba",
  "city": "Curitiba",
  "country": "Brazil",
  "email": "curitiba@pyladies.com",
  "website": "http://brasil.pyladies.com/",
  "photo_url": "https://pyladies.com/assets/images/pyladies-curitiba.png",
  "social_media": {
    "github": "https://github.com/pyladies-curitiba",
    "twitter": "https://twitter.com/pyladiescuritib",
    "facebook": "https://facebook.com/PyLadiesCuritiba"
  }
}
