=== cosimameyer/awesome-pyladies-blogs/scripts/.chapter_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "name":    { "type": "string" },
    "city":    { "type": "string" },
    "country": { "type": "string" },
    "email":   { "type": "string" },
    "website":   { "type": "string" },
    "photo_url": { "type": "string" },
    "social_media": {
      "type": "object",
      "properties": {
        "twitter":   { "type": "string" },
        "facebook":  { "type": "string" },
        "github":    { "type": "string" },
        "linkedin":  { "type": "string" },
        "instagram": { "type": "string" },
        "meetup":    { "type": "string" },
        "mastodon":  { "type": "string" },
        "bluesky":   { "type": "string" },
        "youtube":   { "type": "string" }
      },
      "additionalProperties": false
    }
  },
  "required": ["name", "city", "country"],
  "additionalProperties": false
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-houston-tx.json
{
  "name": "PyLadies Houston",
  "city": "Houston",
  "country": "USA",
  "email": "Houston.pyladies@gmail.com",
  "photo_url": "https://pyladies.com/assets/images/pylady_geek.png",
  "social_media": {
    "twitter": "https://twitter.com/HPyladies",
    "meetup": "https://www.meetup.com/Houston_PyLadies/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-london-uk.json
{
  "name": "PyLadies London",
  "city": "London",
  "country": "United Kingdom",
  "email": "london@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_london.png",
  "social_media": {
    "twitter": "https://twitter.com/PyLadiesLondon",
    "meetup": "https://www.meetup.com/pyladieslondon/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-los-angeles-ca.json
{
  "name": "PyLadies Los Angeles",
  "city": "Los Angeles",
  "country": "USA",
  "email": "la@pyladies.com",
  "website": "https://pyladiesla.netlify.com/",
  "photo_url": "https://pyladies.com/assets/images/pyladies_la.jpeg",
  "social_media": {
    "twitter": "https://twitter.com/pyladiesLA",
    "meetup": "https://www.meetup.com/Pyladies-LA/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-milan-italy.json
{
  "name": "PyLadies Milan",
  "city": "Milan",
  "country": "Italy",
  "email": "milan@pyladies.com",
  "social_media": {
    "twitter": "https://twitter.com/@MilanoPyladies",
    "facebook": "https://facebook.com/pg/pyladiesmilan",
    "meetup": "https://www.meetup.com/meetup-group-AmxqeOPN//"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-duque-de-caxias-rj.json
{
  "name": "PyLadies Duque de Caxias",
  "city": "Duque de Caxias",
  "country": "Brazil",
  "email": "duquedecaxias@pyladies.com",
  "website": "http://duquedecaxias.pyladies.com/",
  "social_media": {
    "github": "https://github.com/pyladies-dcaxias",
    "twitter": "https://twitter.com/PyLadiesCaxias",
    "facebook": "https://facebook.com/PyLadiesDuqueDeCaxias"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-cuernavaca-mxico.json
{
  "name": "PyLadies Cuernavaca",
  "city": "Cuernavaca",
  "country": "Mexico",
  "email": "cuernavaca@pyladies.com",
  "website": "https://pyladies-cuernavaca.quarto.pub/web/",
  "photo_url": "https://pyladies.com/assets/images/pyladies_cuernavaca.png",
  "social_media": {
    "github": "https://github.com/PyLadies-Cuernavaca",
    "twitter": "https://twitter.com/PyLadies_Cuerna"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-cdmx-mxico.json
{
  "name": "PyLadies Mexico City",
  "city": "Mexico City",
  "country": "Mexico",
  "email": "mx@pyladies.com",
  "photo_url": "https://pyladies.com/assets/images/pyladies_cdmx.png",
  "social_media": {
    "twitter": "https://twitter.com/MxPyladies",
    "meetup": "https://www.meetup.com/Mexico-City-Pyladies-Meetup/"
  }
}

=== cosimameyer/awesome-pyladies-blogs/data/chapters/pyladies-athens-greece.json
{
  "name": "PyLadies Athens",
  "city": "Athens",
  "country": "Greece",
  "email": "athens@pyladies.com",
  "social_media": {
    "github": "https://github.com/PyLadies-Athens",
    "linkedin": "https://www.linkedin.com/company/pyladies-athens/",
    "instagram": "https://www.instagram.com/pyladiesathens/"
  }
}
