=== cosimameyer/awesome-pyladies-blogs/scripts/.entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "url":   {"type": "string"},
    "rss_feed": {"type": "string"},
    "type":  {
      "type": "string",
      "enum": ["blog", "youtube", "podcast"]
    },
    "photo_url":   {"type": "string"},
    "description": {"type": "string"},
    "language":    {"type": "string"},
    "authors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "social_media": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "twitter":      {"type": "string"},
                    "mastodon":     {"type": "string"},
                    "bluesky":      {"type": "string"},
                    "linkedin":     {"type": "string"},
                    "facebook":     {"type": "string"},
                    "github":       {"type": "string"},
                    "instagram":    {"type": "string"},
                    "youtube":      {"type": "string"},
                    "tiktok":       {"type": "string"},
                    "periscope":    {"type": "string"},
                    "researchgate": {"type": "string"},
                    "website":      {"type": "string"},
                    "orcid":        {"type": "string"},
                    "meetup":       {"type": "string"}
                  }
                }
              ]
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "url",
    "type",
    "photo_url",
    "authors",
    "language"
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/pyladies-austin.json
{
  "title": "PyLadies Austin",
  "type": "youtube",
  "url": "https://www.youtube.com/channel/UCcpaCF13pUTgi-aWumEnk1Q",
  "photo_url": "https://pyladies.com/assets/images/pyladies_atx.jpeg",
  "language": "en",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCcpaCF13pUTgi-aWumEnk1Q",
  "authors": [
    {
      "name": "PyLadies Austin",
      "social_media": [
        {
          "twitter": "https://twitter.com/pyladiesATX",
          "meetup": "https://www.meetup.com/pyladies-atx/",
          "youtube": "https://www.youtube.com/channel/UCcpaCF13pUTgi-aWumEnk1Q"
        }
      ]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/rio.pyladies.com.json
{
  "title": "PyLadies Rio",
  "type": "blog",
  "url": "https://rio.pyladies.com",
  "photo_url": "https://github.com/PyLadiesRio.png",
  "language": "pt",
  "authors": [
    {
      "name": "PyLadies Rio",
      "social_media": [{
        "github": "PyLadiesRio",
        "twitter": "PyLadiesRio"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/pyladies-soflo.json
{
  "title": "PyLadies SoFlo YouTube channel",
  "type": "youtube",
  "url": "https://www.youtube.com/channel/UCUPLdokEtQlQmbaW9UkJEVQ",
  "photo_url": "https://yt3.googleusercontent.com/d0Q0c1jMSCBrfIGhWgs25pBWmym2UPZO3ex5NiAK6yhwM71AUDfyyAmeoe4xh5-sGuHRz800pw=s176-c-k-c0x00ffffff-no-rj",
  "description": "PyLadies SoFlo YouTube channel. PyLadies SoFlo is a mentoring group with a focus on nurturing gender diversity in the South Florida Python community.",
  "language": "en",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCUPLdokEtQlQmbaW9UkJEVQ",
  "authors": [ 
    {
      "name": "PyLadies South Florida",
      "social_media": [{
        "twitter": "PyLadiesSoFlo",
        "github": "PyLadiesSoFlo",
        "linkedin": "pyladies-soflo",
        "meetup": "pyladies-soflo"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/reshamas.github.io.json
{
  "title": "Reshama Shaikh",
  "type": "blog",
  "url": "https://reshamas.github.io",
  "photo_url": "https://github.com/reshamas.png",
  "language": "en",
  "authors": [
    {
      "name": "Reshama Shaikh",
      "social_media": [{
        "github": "reshamas",
        "twitter": "reshamas"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/blogs/valerybriz.dev.to.json
{
  "title": "Valery C. Briz",
  "type": "blog",
  "url": "https://dev.to/valerybriz",
  "photo_url": "https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/213848/84c58823-8f3e-4848-8091-c04ac5c81d79.jpeg",
  "rss_feed": "https://dev.to/feed/valerybriz",
  "language": "en",
  "authors": [
    {
      "name": "Valery C. Briz",
      "social_media": [{
        "twitter": "valerybriz",
        "mastodon": "@valerybriz@fosstodon.org",
        "github": "valerybriz",
        "linkedin": "valerybriz/"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/pyladies-bh.json
{
  "title": "PyLadies BH",
  "type": "youtube",
  "url": "https://www.youtube.com/channel/UC4S9QWh8o5QeBNgi-UUY3Tw",
  "photo_url": "https://pyladies.com/assets/images/pyladies-bh.png",
  "language": "pt",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UC4S9QWh8o5QeBNgi-UUY3Tw",
  "authors": [
    {
      "name": "PyLadies BH",
      "social_media": [
        {
          "twitter": "https://twitter.com/pyladiesbh",
          "meetup": "https://www.meetup.com/PyLadies-BH-Meetup/",
          "website": "http://bh.pyladies.com",
          "youtube": "https://www.youtube.com/channel/UC4S9QWh8o5QeBNgi-UUY3Tw"
        }
      ]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/pyladies-taiwan.medium.json
{
  "title": "PyLadies Taiwan",
  "type": "blog",
  "url": "https://medium.com/pyladies-taiwan",
  "photo_url": "https://miro.medium.com/v2/resize:fill:128:128/1*E9W29PkuWKmuEpYG9xVoCg.jpeg",
  "rss_feed": "https://medium.com/feed/pyladies-taiwan/tagged/python",
  "language": "zh-TW",
  "authors": [
    {
      "name": "PyLadies Taiwan",
      "social_media": [{
        "website": "https://tw.pyladies.com"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/vadal_.medium.json
{
  "title": "Vasiliki Adalakiari",
  "type": "blog",
  "url": "https://medium.com/@vadal_",
  "photo_url": "https://github.com/vadal.png",
  "rss_feed": "https://medium.com/feed/@vadal_",
  "language": "en",
  "authors": [
    {
      "name": "Vasiliki Adalakiari",
      "social_media": [{
        "github": "vadal",
        "linkedin": "vadalakiari"
      }]
    }
  ]
}
