=== cosimameyer/awesome-pyladies-blogs/scripts/.entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "url":   {"type": "string"},
    "rss_feed": {"type": "string"},
    "type":  {
      "type": "string",
      "enum": ["blog", "youtube", "podcast"]
    },
    "photo_url":   {"type": "string"},
    "description": {"type": "string"},
    "language":    {"type": "string"},
    "authors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "social_media": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "twitter":      {"type": "string"},
                    "mastodon":     {"type": "string"},
                    "bluesky":      {"type": "string"},
                    "linkedin":     {"type": "string"},
                    "facebook":     {"type": "string"},
                    "github":       {"type": "string"},
                    "instagram":    {"type": "string"},
                    "youtube":      {"type": "string"},
                    "tiktok":       {"type": "string"},
                    "periscope":    {"type": "string"},
                    "researchgate": {"type": "string"},
                    "website":      {"type": "string"},
                    "orcid":        {"type": "string"},
                    "meetup":       {"type": "string"}
                  }
                }
              ]
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "url",
    "type",
    "photo_url",
    "authors",
    "language"
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/blog.thea.codes.json
{
  "title": "Thea's blog",
  "type": "blog",
  "url": "https://blog.thea.codes",
  "rss_feed": "https://blog.thea.codes/feed.xml",
  "photo_url": "https://github.com/theacodes.png",
  "language": "en",
  "authors": [
    {
      "name": "Thea Flowers",
      "social_media": [{
        "github": "theacodes",
        "twitter": "theacodes",
        "website": "https://thea.codes/",
        "mastodon": "stargirl@hachyderm.io",
        "bluesky": "theacodes.bsky.social"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/anweshadas.in.json
{
  "title": "Anwesha Das",
  "type": "blog",
  "url": "https://anweshadas.in",
  "photo_url": "http://anweshadas.in/content/images/2016/02/479357_510013835681502_1332101143_o-1.jpg",
  "rss_feed": "https://anweshadas.in/tag/python/rss/",
  "language": "en",
  "authors": [
    {
      "name": "Anwesha Das",
      "social_media": [{
        "twitter": "anweshadassays",
        "linkedin": "anwesha-das-1247121a2"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/blogs/jhylin.github.io.json
{
  "title": "Data in life",
  "type": "blog",
  "url": "https://jhylin.github.io/Data_in_life_blog/",
  "rss_feed": "https://jhylin.github.io/Data_in_life_blog/index-python.xml",
  "photo_url": "https://github.com/jhylin/Data_in_life_blog/blob/main/profile_avatar.jpg",
  "description": "A blog using data science on pharmaceutical and healthcare data",
  "language": "en",
  "authors": [ 
    {
      "name": "Jennifer HY Lin",
      "social_media": [{
         "twitter": "@jenhylin",
         "mastodon": "@jhylin@fosstodon.org",
         "github": "jhylin"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/blogs/aplz.github.io.json
{
  "title": "Anja Pilz",
  "type": "blog",
  "url": "https://aplz.github.io", 
  "photo_url": "https://raw.githubusercontent.com/aplz/aplz.github.io/master/images/avatar_me.jpg", 
  "language": "en",
  "authors": [
    {
      "name": "Anja Pilz", 
      "social_media": [{
         "github": "aplz",
         "website": "https://aplz.github.io",
         "linkedin": "anja-pilz"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/youtube.com.@reshamas.json
{
  "title": "Reshama Shaikh",
  "type": "youtube",
  "url": "https://www.youtube.com/@reshamas",
  "photo_url": "https://github.com/reshamas.png",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCg4KQCow9KAqrAmKb0SxXUA",
  "language": "en",
  "authors": [
    {
      "name": "Reshama Shaikh",
      "social_media": [{
        "github": "reshamas",
        "twitter": "reshamas"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/probablyprivate.com.json
{
  "title": "Katharine Jarmul",
  "type": "blog",
  "url": "https://probablyprivate.com",
  "photo_url": "https://github.com/kjam.png",
  "language": "en",
  "authors": [
    {
      "name": "Katharine Jarmul",
      "social_media": [{
        "github": "kjam",
        "mastodon": "@kjam@chaos.social"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/reshamas.dev.to.json
{
  "title": "Reshama Shaikh",
  "type": "blog",
  "url": "https://dev.to/reshamas",
  "photo_url": "https://github.com/reshamas.png",
  "rss_feed": "https://dev.to/feed/reshamas",
  "language": "en",
  "authors": [
    {
      "name": "Reshama Shaikh",
      "social_media": [{
        "github": "reshamas"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/blogs/dehhmesquita.medium.json
{
    "title": "Déborah Mesquita",
    "type": "blog",
    "url": "https://medium.com/@dehhmesquita",
    "photo_url": "https://avatars.githubusercontent.com/u/2621484?v=4",
    "description": "Blog posts on data science and MLOps",
    "rss_feed": "https://medium.com/feed/@dehhmesquita",
    "language": "en",
    "authors": [
      {
        "name": "Déborah Mesquita",
        "social_media": [{
          "github": "dmesquita",
          "linkedin": "deborahmesquita",
          "website": "https://deborahmesquita.com/"
        }]
      }
    ]
}
