=== cosimameyer/awesome-pyladies-blogs/scripts/.entry_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {"type": "string"},
    "url":   {"type": "string"},
    "rss_feed": {"type": "string"},
    "type":  {
      "type": "string",
      "enum": ["blog", "youtube", "podcast"]
    },
    "photo_url":   {"type": "string"},
    "description": {"type": "string"},
    "language":    {"type": "string"},
    "authors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "social_media": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "twitter":      {"type": "string"},
                    "mastodon":     {"type": "string"},
                    "bluesky":      {"type": "string"},
                    "linkedin":     {"type": "string"},
                    "facebook":     {"type": "string"},
                    "github":       {"type": "string"},
                    "instagram":    {"type": "string"},
                    "youtube":      {"type": "string"},
                    "tiktok":       {"type": "string"},
                    "periscope":    {"type": "string"},
                    "researchgate": {"type": "string"},
                    "website":      {"type": "string"},
                    "orcid":        {"type": "string"},
                    "meetup":       {"type": "string"}
                  }
                }
              ]
            }
          },
          "required": [
            "name"
          ]
        }
      ]
    }
  },
  "required": [
    "title",
    "url",
    "type",
    "photo_url",
    "authors",
    "language"
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/whykay.svbtle.com.json
{
  "title": "Vicky Lee",
  "type": "blog",
  "url": "https://whykay.svbtle.com",
  "photo_url": "https://github.com/whykay.png",
  "rss_feed": "https://whykay.svbtle.com/feed",
  "language": "en",
  "authors": [
    {
      "name": "Vicky Lee",
      "social_media": [{
        "github": "whykay",
        "twitter": "whykay"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/mjmolina.xyz.json
{
  "title": "Maria Jose Molina Contreras",
  "type": "blog",
  "url": "https://mjmolina.xyz",
  "photo_url": "https://github.com/mjmolina.png",
  "rss_feed": "https://mjmolina.xyz/index.xml",
  "language": "en",
  "authors": [
    {
      "name": "Maria Jose Molina Contreras",
      "social_media": [{
        "github": "mjmolina",
        "twitter": "MJ_BIO"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/blogs/whykay-dev.to.json
{
  "title": "whykay @ dev.to",
  "type": "blog",
  "url": "https://dev.to/whykay",
  "photo_url": "https://res.cloudinary.com/practicaldev/image/fetch/s--X3qLsRwL--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/407879/c6e55af6-63e1-4173-bb8c-e504a2a861ad.jpg",
  "language": "en", 
  "rss_feed": "https://dev.to/feed/whykay", 
  "authors": [ 
    {
      "name": "Vicky Twomey-Lee",
      "social_media": [{
         "twitter": "whykay",
         "mastodon": "@whykay@mastodon.ie",
         "github": "whykay",
         "instagram": "theycallmejanie",
         "website": "https://beacons.ai/whykay",
         "linkedin": "vickyleeire"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/pyladies-recife.json
{
  "title": "Pyladies Recife",
  "type": "youtube",
  "url": "https://www.youtube.com/channel/UCNvD7aTKi9Fuyz74wL3Kn9w",
  "photo_url": "https://pyladies.com/assets/images/pyladies_recife.png",
  "language": "pt",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCNvD7aTKi9Fuyz74wL3Kn9w",
  "authors": [
    {
      "name": "Pyladies Recife",
      "social_media": [
        {
          "twitter": "https://twitter.com/pyladiesrecife",
          "github": "https://github.com/pyladies-brazil",
          "facebook": "https://facebook.com/PyLadies-Recife",
          "website": "http://brasil.pyladies.com",
          "youtube": "https://www.youtube.com/channel/UCNvD7aTKi9Fuyz74wL3Kn9w"
        }
      ]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/pyladies-munich.json
{
  "title": "Munich PyLadies",
  "type": "youtube",
  "url": "https://www.youtube.com/channel/UCiYzIa3vGRYi9R3Ynaf20Cw",
  "photo_url": "https://pyladies.com/assets/images/pyladiesmu_logo.png",
  "language": "en",
  "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCiYzIa3vGRYi9R3Ynaf20Cw",
  "authors": [
    {
      "name": "Munich PyLadies",
      "social_media": [
        {
          "twitter": "https://twitter.com/pyladiesmunich",
          "meetup": "https://www.meetup.com/PyLadiesMunich/",
          "github": "https://github.com/pyladiesmunich",
          "youtube": "https://www.youtube.com/channel/UCiYzIa3vGRYi9R3Ynaf20Cw"
        }
      ]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/afimaamedufie.hashnode.dev.json
{
  "title": "Abigail Afi Gbadago",
  "type": "blog",
  "url": "https://afimaamedufie.hashnode.dev",
  "photo_url": "https://github.com/AfiMaameDufie.png",
  "rss_feed": "https://medium.com/feed/@afimaamedufie",
  "language": "en",
  "authors": [
    {
      "name": "Abigail Afi Gbadago",
      "social_media": [{
        "github": "AfiMaameDufie",
        "twitter": "afi_maame",
        "mastodon": "@afimaame@mastodon.social"
      }]
    }
  ]
}

=== cosimameyer/awesome-pyladies-blogs/data/content/pyladies-blr.json
{
    "title": "PyLadies Bangalore",
    "type": "youtube",
    "url": "https://www.youtube.com/@pyladiesbengaluru7366",
    "photo_url": "https://raw.githubusercontent.com/cosimameyer/awesome-pyladies-creations/main/img/pyladies_blr_logo.jpeg",
    "rss_feed": "https://www.youtube.com/feeds/videos.xml?channel_id=UCRF8Cf4Ppe4OFed4zbgujjg",
    "language": "en", 
    "authors": [ 
      {
        "name": "PyLadies Bangalore",
        "social_media": [{
           "twitter": "pyladiesblr",
           "youtube": "pyladiesbengaluru7366",
           "website": "https://pyladies.com/locations/blr/",
           "meetup": "PyLadies-Bangalore-Chapter"
        }]
      }
    ]
  }

=== cosimameyer/awesome-pyladies-blogs/data/content/jjablonski.realpython.json
{
  "title": "Joanna Jablonski at Real Python",
  "type": "blog",
  "url": "https://realpython.com/team/jjablonski/",
  "photo_url": "https://files.realpython.com/media/jjablonksi-avatar.e37c4f83308e.jpg",
  "rss_feed": "https://realpython.com/atom.xml",
  "language": "en",
  "authors": [
    {
      "name": "Joanna Jablonski",
      "social_media": [{
        "github": "jablonskidev",
        "twitter": "Jo_Jablonski"
      }]
    }
  ]
}
